# history
HISTFILE=~/.zsh_history
HISTSIZE=100
SAVEHIST=100
setopt hist_ignore_dups
setopt hist_ignore_space
setopt share_history
setopt append_history

# behavior
setopt autocd
setopt extendedglob
setopt correct

# completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# prompt: user@host cwd (git branch) $
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats ' (%b)'
setopt prompt_subst
PROMPT='%F{cyan}%n@%m%f %F{blue}%~%f%F{yellow}${vcs_info_msg_0_}%f %# '

# environment
export EDITOR=vim
export PAGER=less
export LESS='-R'

# aliases
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -lha'
alias grep='grep --color=auto'

# fzf integration, if installed
for fzf_init in /usr/share/doc/fzf/examples/key-bindings.zsh /usr/share/fzf/key-bindings.zsh; do
    [[ -r "$fzf_init" ]] && source "$fzf_init"
done
for fzf_comp in /usr/share/doc/fzf/examples/completion.zsh /usr/share/fzf/completion.zsh; do
    [[ -r "$fzf_comp" ]] && source "$fzf_comp"
done
