# history
HISTFILE=~/.zsh_history
HISTSIZE=100
SAVEHIST=100
setopt hist_ignore_dups
setopt hist_ignore_space
setopt share_history
setopt append_history

# behavior
setopt autocd
setopt extendedglob
setopt correct

# vim keybindings
bindkey -v
export KEYTIMEOUT=1

# cursor shape: block in normal mode, beam in insert mode
function zle-keymap-select {
    if [[ $KEYMAP == vicmd ]]; then
        echo -ne '\e[2 q'
    else
        echo -ne '\e[6 q'
    fi
}
zle -N zle-keymap-select
zle-line-init() { echo -ne '\e[6 q' }
zle -N zle-line-init

# keep common emacs-style bindings usable in insert mode
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^R' history-incremental-search-backward

# edit current command line in $EDITOR with 'v' in normal mode
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

# completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# prompt: user@host cwd (git branch) $
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats ' (%b)'
setopt prompt_subst
PROMPT='%F{cyan}%n@%m%f %F{blue}%~%f%F{yellow}${vcs_info_msg_0_}%f %# '

# environment
export EDITOR=vim
export PAGER=less
export LESS='-R'
export COLORTERM=truecolor

# aliases
alias ls='ls --color=auto'
alias ll='ls -lh'
alias l='ls -lha'
alias grep='grep --color=auto'
alias keep-alive='touch ~/.ai-keep-alive && exit'
